# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-10 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename__githubuser__to__user'),
        ('djstripe', '0029_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djstripe_customers', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
