# Generated by Django 2.0.13 on 2020-05-06 15:17

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0031_handle_3d_secure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripesource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='card',
            name='three_d_secure',
            field=djstripe.fields.StripeTextField(help_text='State of 3D secure requirement', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.'),
        ),
    ]
